MODULE_PATH="/data/adb/modules/smartdns"
DATA_PATH="/data/adb/smartdns"
BUSYBOX_BIN="$DATA_PATH/bin/busybox"
SCRIPTS_PATH="$DATA_PATH/scripts"
BIN_PATH="$DATA_PATH/bin"
SMARTDNS_PATH="$DATA_PATH/smartdns"
SMARTDNS_BIN="smartdns"
SMARTDNS_CONF="$SMARTDNS_PATH/smartdns.conf"
RUN_PATH="$DATA_PATH/run"
LIB_PATH="$BIN_PATH/lib"
RULES_PATH="$SMARTDNS_PATH/rules"

# 开机运行
# 启用/禁用(true/false)
AUTO_RUN=true

# CPU 亲和性
# 格式: 单核=0  范围=0-3  多个=0,2,4
CPU_AFFINITY=0-5

# OOM 保护（防止系统内存不足时杀死 SmartDNS）
# 启用/禁用(true/false)
OOM_PROTECT=true

# 是否启用规则自动定时更新
# 启用/禁用(true/false)
RULE_AUTO_UPDATE=true

# 每天执行更新的时间（24小时制，格式 HH:MM）
RULE_UPDATE_TIME=12:00

# 规则列表
# NAME : 规则文件名（保存到 smartdns/rules/ 目录下）
# URL  : 规则下载地址
# 规则引用需在配置文件中修改，默认anti-ad
# 下载多个文件，套公式复制即可

# anti-ad
RULE1_NAME=anti-ad-for-smartdns.conf
RULE1_URL=https://anti-ad.net/anti-ad-for-smartdns.conf

# 秋风
RULE2_NAME=AWAvenue-Ads-Rule.conf
RULE2_URL=https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-SmartDNS.conf


