# DNS 服务器监听的 IP 和端口
bind [::]:1451 -g direct

# 日志
log-level error
log-file ../../run/smartdns.log
log-size 512k
log-num 5

#审计日志
audit-enable no
audit-num 16
audit-size 16M
audit-file ../../run/smartdns-audit.log

# DNS 缓存大小
# 0 表示无缓存，-1表示根据内存大小自动调整
cache-size -1

# 缓存持久化
cache-persist yes

# 缓存文件
cache-file data/smartdns.cache

# 缓存自动保存时间
cache-checkpoint-time 7200

# 域名预获取
prefetch-domain yes

# 过期缓存预获取时间
serve-expired-prefetch-time 10800

# 乐观缓存
serve-expired yes

# 响应过期请求时使用的 TTL 值
serve-expired-reply-ttl 5

# 过期缓存超时时间
serve-expired-ttl 86400

# 速度检查模式
speed-check-mode tcp:80,tcp:443

# 响应模式（first-ping|fastest-ip|fastest-response）
response-mode first-ping

# 是否禁用ipv6
force-AAAA-SOA no

# 双栈 IP 优选
dualstack-ip-selection yes

#是否允许纯IPV6地址
dualstack-ip-allow-force-AAAA yes

# 如需要倾向使用IPV6，请调整阈值，单位为ms，两个IP地址的速度阈值大于配置值时，才会进行优选
dualstack-ip-selection-threshold 15

# 所有资源记录的 TTL
rr-ttl-min 60
rr-ttl-max 3600
rr-ttl-reply-max 300

# 外部规则集引用
# anti-ad
conf-file /data/adb/smartdns/smartdns/rules/anti-ad-for-smartdns.conf

#全局配置ipset，所有解析得到的ip添加进cnip，搭配boxproxy绕过cnip，如需使用取消注释
#ipset #4:cnip,#6:cnip6

#edns-client-subnet 114.114.114.114/23

# Bootstrap 服务器
server 223.5.5.5 -b -g direct
server 1.12.12.12 -b -g direct


# 直连 dns
server-https https://doh.pub/dns-query -e -g direct 
server-https https://dns.alidns.com/dns-query -e -g direct 
server-https https://doh.360.cn/dns-query -e -g direct 
server-h3 h3://dns.alidns.com/dns-query -e -g direct
server-quic 223.5.5.5 -e -g direct
#server-https https://doh-pure.onedns.net/dns-query -e -g direct 
#server-https https://dns.alidns.com/dns-query -e -g direct -subnet-all-query-types

# 数据库
data-dir data

# WebUI
plugin smartdns_ui.so
smartdns-ui.www-root wwwroot
smartdns-ui.ip http://127.0.0.1:6080
smartdns-ui.token-expire 600
smartdns-ui.max-query-log-age 31536000
smartdns-ui.enable-terminal no
smartdns-ui.enable-cors yes

# WebUI 账密
smartdns-ui.user root
smartdns-ui.password root